#! /usr/bin/env ansible-playbook
# Uninstall tmux terminal multiplexer
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: tmux | uninstall
  hosts: tmux
  tasks:
  - include_role:
      name: tmux
      tasks_from: uninstall.yml
    tags:
    - tmux
